### ISSUE TITLE
Why not generate fake faces to protect privacy?

### ISSUE THREAD

**Issue by ZhangXGe** [princetonvisualai/imagenet-face-obfuscation#3] opened 2021-04-08 03:20 UTC
Why not generate fake faces for privacy protection?

**Comment by yangky11** [comment] 2021-04-08 13:10
Generating fake faces (e.g., using GANs) is tricky. The GAN needs to be trained on another dataset of human faces. There could be privacy and fairness issues related to the training process. That's one of the reasons we decided to use simple obfuscation methods (e.g., blurring) not based on machine learning.

**Comment by yangky11** [comment] 2021-04-08 13:16
I'm closing this issue since we use Github Issues only for reproducibility and bug fixes. For broader questions about the paper, you're welcome to send us emails.

**Closed as completed by yangky11** 2021-04-08 13:16 UTC

**Comment by ZhangXGe** [comment] 2021-04-08 13:17
Thanks for the reply, this solves my question.
